# Nexus98 Scribe TOC Generator
# Part of Nexus98 External Scribe Framework
# Version: 1.0.0

<#
.SYNOPSIS
    Generates Table of Contents for all documentation

.DESCRIPTION
    Scans all markdown files and generates a structured TOC.
    Designed for clean absorption into mature Nexus98.
#>

function Invoke-Nexus98ScribeTOC {
    param(
        [hashtable]$Config,
        [string]$OutputPath,
        [string]$Root = (Resolve-Path ".").Path
    )

    Write-Host "[Nexus98 Scribe TOC] Generating..." -ForegroundColor Cyan

    # Load core module if not already loaded
    $corePath = Join-Path (Split-Path $MyInvocation.MyCommand.Path -Parent) "Nexus98_Scribe_Core.ps1"
    if (-not $corePath) { $corePath = Join-Path (Resolve-Path ".").Path "core\Nexus98_Scribe_Core.ps1" }
    if (Test-Path $corePath) {
        . $corePath
    }

    $snapshot = Get-Nexus98FullSnapshot -RootPath $Root -Config $Config

    $toc = @{
        generated  = (Get-Date).ToString('o')
        version    = "1.0.0"
        root       = $Root
        sections   = @()
    }

    # Core modules section
    $toc.sections += Build-TOCSection -Title "Core Modules" -Path (Join-Path $Root "core") -Root $Root

    # Tests section
    $toc.sections += Build-TOCSection -Title "Tests" -Path (Join-Path $Root "tests") -Root $Root

    # Configuration section
    $toc.sections += Build-TOCSection -Title "Configuration" -Path (Join-Path $Root "config") -Root $Root

    # Documentation section
    $toc.sections += Build-TOCSection -Title "Documentation" -Path (Join-Path $Root "docs") -Root $Root

    # Knowledge base section
    $toc.sections += Build-TOCSection -Title "Knowledge Base" -Path (Join-Path $Root "Knowledge") -Root $Root

    # Scripts section
    $toc.sections += Build-TOCSection -Title "Scripts" -Path (Join-Path $Root "scripts") -Root $Root

    # Reports section
    $toc.sections += Build-TOCSection -Title "Reports" -Path (Join-Path $Root "reports") -Root $Root

    # GUARDIAN_HANDOFF section
    $handoffPath = Join-Path $Root "GUARDIAN_HANDOFF"
    if (Test-Path $handoffPath) {
        $toc.sections += Build-TOCSection -Title "Guardian Handoff" -Path $handoffPath -Root $Root
    }

    # GUARDIAN_UPLOAD_PACKAGE section
    $uploadPath = Join-Path $Root "GUARDIAN_UPLOAD_PACKAGE"
    if (Test-Path $uploadPath) {
        $toc.sections += Build-TOCSection -Title "Guardian Upload Package" -Path $uploadPath -Root $Root
    }

    # Write outputs
    $tocPath = Join-Path $OutputPath "TOC.md"
    $tocJsonPath = Join-Path $OutputPath "TOC.json"

    ConvertTo-MarkdownTOC -TOC $toc | Set-Content $tocPath -Encoding UTF8
    $toc | ConvertTo-Json -Depth 10 | Set-Content $tocJsonPath -Encoding UTF8

    Write-Host "[TOC] Written to $tocPath" -ForegroundColor Green

    return $toc
}

function Build-TOCSection {
    param(
        [string]$Title,
        [string]$Path,
        [string]$Root
    )

    if (-not (Test-Path $Path)) {
        return @{
            title  = $Title
            path   = $Path.Substring($Root.Length + 1)
            count  = 0
            items  = @()
        }
    }

    $files = @(Get-ChildItem $Path -Filter "*.md" -Recurse -ErrorAction SilentlyContinue | Sort-Object FullName)

    $section = @{
        title  = $Title
        path   = $Path.Substring($Root.Length + 1)
        count  = $files.Count
        items  = @()
    }

    foreach ($f in $files) {
        $relPath = $f.FullName.Substring($Root.Length + 1)
        $content = Get-Content $f.FullName -TotalCount 5 -Raw -ErrorAction SilentlyContinue
        $title = if ($content -match '^#\s+(.+)') { $matches[1] } else { $f.BaseName }

        $section.items += @{
            title    = $title
            file     = $f.BaseName
            path     = $relPath
            size     = $f.Length
            modified = $f.LastWriteTime.ToString('o')
        }
    }

    return $section
}

function ConvertTo-MarkdownTOC {
    param([hashtable]$TOC)

    $md = @()
    $md += "# Nexus98 Documentation - Table of Contents"
    $md += ""
    $md += "> Generated: $($TOC.generated)"
    $md += "> Version: $($TOC.version)"
    $md += ""

    foreach ($section in $TOC.sections) {
        $md += "## $($section.title) ($($section.count) files)"
        $md += ""

        foreach ($item in $section.items) {
            $md += "- [$($item.title)]($($item.path))  \n  \`\` $($item.modified) | $($item.size) bytes"
        }
        $md += ""
    }

    $md += "---"
    $md += ""
    $md += "*Auto-generated by Nexus98 Scribe v1.0.0*"

    return $md -join "`n"
}